//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameKash {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameKash.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action has been successfully discarded..
        /// </summary>
        internal static string ActionDiscarded {
            get {
                return ResourceManager.GetString("ActionDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not dead..
        /// </summary>
        internal static string CharacterNotDead {
            get {
                return ResourceManager.GetString("CharacterNotDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not paralysed..
        /// </summary>
        internal static string CharacterNotParalysed {
            get {
                return ResourceManager.GetString("CharacterNotParalysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not poisoned..
        /// </summary>
        internal static string CharacterNotPoisoned {
            get {
                return ResourceManager.GetString("CharacterNotPoisoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not sick..
        /// </summary>
        internal static string CharacterNotSick {
            get {
                return ResourceManager.GetString("CharacterNotSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Age value..
        /// </summary>
        internal static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Health value..
        /// </summary>
        internal static string InvalidHealth {
            get {
                return ResourceManager.GetString("InvalidHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mana value..
        /// </summary>
        internal static string InvalidMana {
            get {
                return ResourceManager.GetString("InvalidMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name..
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered power value is invalid..
        /// </summary>
        internal static string InvalidPowerValue {
            get {
                return ResourceManager.GetString("InvalidPowerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t recognise this command. Please try again..
        /// </summary>
        internal static string InvalidUserCmd {
            get {
                return ResourceManager.GetString("InvalidUserCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This artefact has already been used and can&apos;t be renewed..
        /// </summary>
        internal static string IsNotRenewable {
            get {
                return ResourceManager.GetString("IsNotRenewable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough mana..
        /// </summary>
        internal static string LowMana {
            get {
                return ResourceManager.GetString("LowMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This artefact can&apos;t be used. This item&apos;s power is 0..
        /// </summary>
        internal static string NullItemPower {
            get {
                return ResourceManager.GetString("NullItemPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This artefact can only be applied to a wizard..
        /// </summary>
        internal static string OnlyForWizard {
            get {
                return ResourceManager.GetString("OnlyForWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! You are about to cast this spell on your hero. This will decrease your OWN hero&apos;s health. Type &quot;Y&quot; if you wish to proceed. Type &quot;N&quot; if you wish to discard this action..
        /// </summary>
        internal static string SelfDamageWarning {
            get {
                return ResourceManager.GetString("SelfDamageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is not dead..
        /// </summary>
        internal static string WizardNotDead {
            get {
                return ResourceManager.GetString("WizardNotDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is not paralysed..
        /// </summary>
        internal static string WizardNotParalysed {
            get {
                return ResourceManager.GetString("WizardNotParalysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is not poisoned..
        /// </summary>
        internal static string WizardNotPoisoned {
            get {
                return ResourceManager.GetString("WizardNotPoisoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is not sick..
        /// </summary>
        internal static string WizardNotSick {
            get {
                return ResourceManager.GetString("WizardNotSick", resourceCulture);
            }
        }
    }
}
